[package]
name = "template-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.template]
path = ".."

[dependencies.elrond-wasm]
version = "0.23.0"

[dependencies.elrond-wasm-debug]
version = "0.23.0"
